import BAND from './thumbnails/BAND.png';
import CIRCULAR_OVERVIEW_LINEAR_DETAIL from './thumbnails/CIRCULAR_OVERVIEW_LINEAR_DETAIL.gif';
import CYTOBANDS from './thumbnails/CYTOBANDS.png';
import MARK_DISPLACEMENT from './thumbnails/MARK_DISPLACEMENT.png';
import MATRIX from './thumbnails/MATRIX.png';
import RESPONSIVE_COMPARATIVE_MATRICES from './thumbnails/RESPONSIVE_COMPARATIVE_MATRICES.gif';
import RESPONSIVE_MULTIVEC from './thumbnails/RESPONSIVE_MULTIVEC.gif';
import RULE from './thumbnails/RULE.png';
import VISUAL_ENCODING from './thumbnails/VISUAL_ENCODING.png';
import VISUAL_ENCODING_CIRCULAR from './thumbnails/VISUAL_ENCODING_CIRCULAR.png';

export const THUMBNAILS = {
    BAND,
    CIRCULAR_OVERVIEW_LINEAR_DETAIL,
    CYTOBANDS,
    MARK_DISPLACEMENT,
    MATRIX,
    RESPONSIVE_COMPARATIVE_MATRICES,
    RESPONSIVE_MULTIVEC,
    RULE,
    VISUAL_ENCODING,
    VISUAL_ENCODING_CIRCULAR
};
