name: Semantic Pull Request

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Configure which types are allowed (newline-delimited).
          types: |
            feat
            fix
            ci
            chore
            docs
            refactor
            test
            perf
          # Configure which scopes are allowed.
          scopes: |
            core
            track
            data-fetcher
            api
            editor
          # Configure if a scope must always be provided.
          requireScope: true
          # Configure which scopes are disallowed in PR titles (newline-delimited).
          # Anything but `feat` and `fix`
          disallowScopes: |
            ci
            chore
            docs
            refactor
            test
