name: Update Snapshots

on:
  issue_comment:
    types: [created]

jobs:
  update_snapshots:
    if: github.event.comment.body == '/update-snapshots' && github.event.issue.pull_request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your steps here to update snapshots
      - name: Update snapshots
        run: echo "Updating snapshots..."
