export { addDummyTrack } from './dummy-track-example';
export { addTextTrack } from './text-track-example';
export { addCircularBrush } from './circular-brush-example';
export { addGoslingTrack } from './gosling-track-example';
export { addAxisTrack } from './axis-track-example';
export { addLinearBrush } from './brush-linear-example';
export { addBigwig } from './bigwig-data-example';
export { addHeatmap } from './heatmap-example';
export { addLeftAxisTrack } from './left-track-example';
